# Generated by Django 5.0.6 on 2024-05-29 11:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_pretplata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutsesijazapis',
            name='user',
        ),
        migrations.AddField(
            model_name='checkoutsesijazapis',
            name='user_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
