# Generated by Django 5.0.6 on 2024-06-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='role',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
