# Generated by Django 5.0.6 on 2024-06-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi_generator', '0004_alter_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='midi_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
