# Generated by Django 5.0.6 on 2024-06-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi_generator', '0005_chat_midi_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='type',
            field=models.CharField(blank=True, default='user', max_length=255, null=True),
        ),
    ]
